# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.CharField(max_length=100, null=True)),
                ('string2', models.CharField(max_length=100, null=True)),
                ('string3', models.CharField(max_length=100, null=True)),
                ('string4', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
